version: '3.7'

services:

  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
      - ./.docker/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
    volumes:
      - .:/var/www/html